export const cuisinesObj: any = {
    Italian: ["Pizzeria", "Italian Restaurant"],
    American: [
        "Fast Food Restaurant",
        "Steakhouse",
        "Diner",
        "Burger Joint",
        "American Restaurant",
        "South American Restaurant",
        "Peruvian Roast Chicken Joint",
        "Caribbean Restaurant",
        "Peruvian Restaurant",
        "Latin American Restaurant",
        "Fried Chicken Joint",
        "BBQ Joint",
        "Argentinian Restaurant",
        "Sandwich Spot",
        "Brazilian Restaurant",
        "Hawaiian Restaurant",
        "New American Restaurant",
        "Australian Restaurant"
    ],
    Arabian: [
        "Lebanese Restaurant",
        "Ethiopian Restaurant",
        "Falafel Restaurant",
        "Middle Eastern Restaurant",
        "Persian Restaurant",
        "Mediterranean Restaurant",
        "African Restaurant",
        "Egyptian Restaurant",
        "Kurdish Restaurant",
        "Afghan Restaurant"
    ],
    Bar: [
        "Bar",
        "Wine Bar",
        "Pub",
        "Cocktail Bar",
        "Beer Bar",
        "Brewery",
        "Hotel Bar",
        "Dive Bar",
        "Night Club",
        "Lounge",
        "Beer Garden",
        "Sports Bar",
        "Karaoke Bar",
        "Sake Bar"
    ],
    Dessert: [
        "Cafe",
        "Bakery",
        "Cafe, Coffee, and Tea House",
        "Dessert Shop",
        "Coffee Shop",
        "Ice Cream Parlor",
        "Pastry Shop",
        "Bistro"
    ],
    Indian: [
        "Indian Restaurant",
        "Pakistani Restaurant",
        "Indie Movie Theater",
        "Street Food Gathering"
    ],
    English: ["English Restaurant", "Fish and Chips Shop", "Tea Room"],
    European: [
        "Modern European Restaurant",
        "Venezuelan Restaurant",
        "French Restaurant",
        "Russian Restaurant",
        "Eastern European Restaurant",
        "Greek Restaurant",
        "Turkish Restaurant",
        "Portuguese Restaurant",
        "Tapas Restaurant",
        "Taco Restaurant",
        "Southern Food Restaurant",
        "Arepa Restaurant",
        "Deli",
        "Scandinavian Restaurant",
        "Plaza",
        "German Restaurant",
        "Spanish Restaurant",
        "Polish Restaurant",
        "Belgian Restaurant"
    ],
    Asian: [
        "Thai Restaurant",
        "Vietnamese Restaurant",
        "Seafood Restaurant",
        "Farmers Market",
        "Ramen Restaurant",
        "Cantonese Restaurant",
        "Malay Restaurant",
        "Sushi Restaurant",
        "Japanese Restaurant",
        "Udon Restaurant",
        "Chinese Restaurant",
        "Korean Restaurant",
        "Shaanxi Restaurant",
        "Szechuan Restaurant",
        "Asian Restaurant",
        "Sri Lankan Restaurant",
        "Dim Sum Restaurant",
        "Dumpling Restaurant",
        "Soup Spot"
    ],
    Miscellaneous: [
        "Restaurant",
        "Gastropub",
        "Speakeasy",
        "Grocery Store",
        "Food and Beverage Service",
        "Food and Beverage Retail",
        "Arts and Entertainment",
        "Amusement Park",
        "Education",
        "Imported Food Store",
        "Theater",
        "Gourmet Store"
    ],
    Vegan: ["Vegan and Vegetarian Restaurant", "Salad Restaurant"]
} 